#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Flatten": "04_vae.ipynb",
         "UnFlatten": "04_vae.ipynb",
         "VAE": "04_vae.ipynb",
         "vae_loss": "04_vae.ipynb"}

modules = ["models\_vae.py"]

git_url = "https://github.com/pmaxit/dlnotebooks/tree/master/"

def custom_doc_links(name): return None