# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "SimpleCNN": "01_simpleCNN.ipynb"}

modules = ["core.py",
           "models/simplecnn.py"]

doc_url = "https://pmaxit.github.io/dlnotebooks/"

git_url = "https://github.com/pmaxit/dlnotebooks/tree/master/"

def custom_doc_links(name): return None