#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'helloSayer', 'helloname']

#Cell
from fastscript import call_parse, Param

#Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello to {to}!'

#Cell
class helloSayer:
    " Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to
    def say(self):
        "Do the saying"
        return say_hello(self.to)

#Cell
@call_parse
def helloname(fname: Param("A notebook name or globe to convert", str)=None):
    print("hello world")